#pragma once

#include "NativeGameplayTags.h"

namespace PushGameplayTags
{
	// Ability
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Crunch_Uppercut);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Crunch_GroundBlast);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Countess_Infiltrate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Countess_Siphon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Countess_Execute);

	// Cooldown
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability_Crunch_Uppercut);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability_Crunch_GroundBlast);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability_Countess_Infiltrate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability_Countess_Siphon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability_Countess_Execute);

	// Input
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_BasicAttack_Pressed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_SecondaryAttack_Pressed);

	// Gameplay Events
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Ability_Window_Launch);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Ability_Window_Stealth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Ability_Combo_Change);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Ability_Combo_Change_Combo02);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Ability_Combo_Change_Combo03);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Ability_Combo_Change_Combo04);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Ability_Combo_Change_End);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Ability_Combo_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Status_Launch);

	// Status
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stun);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Launched);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stealth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Aiming);

	// Gameplay Cues
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_CameraShake);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Status_Stealth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Status_Stealth_Countess_Infiltrate);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Crunch_Punch);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Crunch_GroundBlast);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Countess_Basic);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Countess_Finish);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Countess_Siphon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Countess_Ultimate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Minion);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Reaction);
}
